# Generated by Django 2.2 on 2019-04-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
